spring:
  profiles:
    active: dev
    group:
      prod:
        - secret
        - common
      dev:
        - secret
        - common
      local:
        - secret
        - common
      prd:
        - secret
        - common


