spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.camx7rzwhqih.ap-northeast-2.rds.amazonaws.com:3306/lv5?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: qwer1234
