### 1. 상품등록 API

POST http://localhost:9090/products/register
Content-Type: application/json

{
    "name":"나이키 데이브레이크 CK2351 101",
    "price":74350,
    "quantity":1,
    "info":"NIKE 운동화",
    "category":"스포츠"
}

### 1-1. 상품등록2 API
POST http://localhost:9090/products/register
Content-Type: application/json

{
  "name":"애플워치 SE4",
  "price":4200000,
  "quantity":1,
  "info":"신제품 애플워치",
  "category":"디지털/가전"
}

### 2. 선택한 상품조회 API
GET http://localhost:9090/products/2


### 3. 상품조회 API
GET http://localhost:9090/products

### 4. 상품 페이징 처리
GET http://localhost:9090/products?page=0&orderby=price&sort=ASC